# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: cwdevwork/cw_php8fpm-buster:v0.0.1

    steps:
      - checkout

      # composer cache
      - restore_cache:
          keys:
            # "composer.json" can be used if "composer.json"
            # is not committed to the repository.
            - composer-v1-{{ checksum "composer.lock" }}
            # fallback to using the latest cache if no exact match is found
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # node cache
#      - restore_cache:
#          keys:
#            - node-v4-{{ checksum "package.json" }}
#            - node-v4-
#      - run: npm install
#      - save_cache:
#          key: node-v4-{{ checksum "package.json" }}
#          paths:
#            - node_modules
#            - ~/.yarn
#
#      # prepare .env
#      - run: mv .env.testing .env
#
#      # prepare the database
#      - run: touch ./database/database.sqlite
#      - run: php artisan migrate --env=testing --force

      - run:
          name: run tests with phpunit
          command: php ./vendor/bin/phpunit tests
